services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    environment:
      - CORS_ORIGINS=http://localhost:5173
      - DATABASE_URL=postgresql+psycopg://notes:notes@db:5432/notes
      - WEBSOCKET_URL=ws://localhost:8000/ws
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
    working_dir: /code
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=notes
      - POSTGRES_PASSWORD=notes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
