services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - devcontainer-node-modules:/workspace/frontend/node_modules
      - devcontainer-python-packages:/usr/local/lib/python3.11/site-packages
    command: sleep infinity
    depends_on:
      - db
    environment:
      - VITE_API_URL=http://localhost:8000
      - CORS_ORIGINS=http://localhost:5173

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=notes
      - POSTGRES_PASSWORD=notes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  devcontainer-node-modules:
  devcontainer-python-packages: